version: '3.3'

services:
  
  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 0JjV5(G26,^{a&L8
      POSTGRES_USER: identity
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  logger:
    image: stefanfcb94/musicplayer-logger-service:latest
    restart: always
    command: node dist/index.js
    volumes:
      - ./config:/config
      - ./data/logs:/usr/src/service/logs
    environment:
      - USE_HTTPS=true
      - CERTIFICATE_FILE=/config/ssl/musicserver.crt
      - PRIVATE_KEY_FILE=/config/ssl/musicserver.key
      - LOGGER_HTTP_PORT=80
      - LOGGER_HTTPS_PORT=443
      - LOGGER_HTTP_SOCKET_PORT=8080
      - LOGGER_HTTPS_SOCKET_PORT=8443
      - DB_HOST=db
      - DB_PORT=5432
      - LOGGER_DB_USERNAME=logger
      - LOGGER_DB_PASSWORD=logger
      - LOGGER_DB_DATABASE=logger
    ports:
      - 9000:80
      - 9001:443
      - 9002:8080
      - 9003:8443
    depends_on:
      - "db"

  dev:
    image: node:11-alpine
    volumes: 
      - .:/usr/src/service
      - ./config:/usr/src/service/config
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8443:8443
    depends_on:
      - "db"
      - "logger"
    environment:
      - NODE_ENV=development
      - LOGGER_HTTP_PORT=80
      - LOGGER_HTTPS_PORT=443
      - LOGGER_HTTP_SOCKET_PORT=8080
      - LOGGER_HTTPS_SOCKET_PORT=8443
      - DB_HOST=db
      - DB_PORT=5432
      - AUTH_DB_USERNAME=auth
      - AUTH_DB_PASSWORD=auth
      - AUTH_DB_DATABASE=auth
